import Foundation
import Combine
import CollabTermC

/// Thin Swift wrapper around the C ABI session (`ct_session_*`). Owns the
/// handle, runs a timer-driven poll loop, decodes inbound frames with
/// `FrameCodec`, and exposes role-specific state (`participants`, public URL)
/// for the UI.
///
/// Topology: star. Peers connect to the host; the host is authoritative for
/// the roster and re-broadcasts it whenever someone joins or leaves. Peers
/// read `participants` from the last Roster frame; the host maintains it
/// from Hello frames + lifecycle events.
@MainActor
final class SessionManager: ObservableObject {
    enum Role: Equatable {
        case host
        case peer
    }

    enum State: Equatable {
        case idle
        case starting
        case running
        case reconnecting(attempt: Int)  // peer-only: connection dropped, auto-retrying
        case disconnected  // peer-only: host went away
        case failed(String)
    }

    /// Who's in the session (host + peers), by user identity. Name, color,
    /// and role come from Hello frames. On peers, this list arrives via
    /// Roster broadcasts from the host.
    struct Participant: Identifiable, Equatable {
        var id: UserIdentity { identity }
        var identity: UserIdentity
        var role: SessionRole
        var name: String
        var color: UInt32
    }

    @Published private(set) var role: Role = .host
    @Published private(set) var state: State = .idle
    @Published private(set) var participants: [Participant] = []
    @Published private(set) var localPort: UInt16 = 0
    @Published private(set) var publicURL: String?
    @Published var lastError: String?

    /// Bore relay hostname injected at build time from Secrets.xcconfig.
    static let defaultBoreServer: String = {
        Bundle.main.infoDictionary?["CTBoreServer"] as? String ?? ""
    }()

    /// Bore secret injected at build time from Secrets.xcconfig.
    static let boreSecret: String = {
        Bundle.main.infoDictionary?["CTBoreSecret"] as? String ?? ""
    }()

    /// Bore relay server hostname. Persisted across launches.
    @Published var boreServer: String = {
        UserDefaults.standard.string(forKey: "CoTTY.boreServer") ?? SessionManager.defaultBoreServer
    }() {
        didSet {
            guard boreServer != oldValue else { return }
            UserDefaults.standard.set(boreServer, forKey: "CoTTY.boreServer")
        }
    }

    /// Last mode broadcast by the host. Peers consult this to decide whether
    /// to drop keystrokes and surface a creator-only banner. Defaults to
    /// `.line` so a fresh peer allows input until it hears otherwise.
    @Published private(set) var remoteMode: TermMode = .line

    /// Active access policy.
    /// * Host: source of truth, persisted via UserDefaults
    ///   (`accessModeDefaultsKey`). Toggling it broadcasts an
    ///   `accessMode` frame so peers see the change immediately.
    /// * Peer: shadow copy, updated whenever the host broadcasts
    ///   `accessMode`. Defaults to `.full` so a fresh peer allows
    ///   input until it hears otherwise (matching `remoteMode`).
    @Published private(set) var accessMode: AccessMode = .full

    /// End-to-end encryption key for this session. Generated by the host
    /// and embedded in the share URL; peers set it before calling joinPeer.
    /// Nil means no encryption (no key in URL).
    var sessionKey: SessionKey?

    let localIdentity: UserIdentity
    @Published var localName: String {
        didSet {
            guard oldValue != localName, handle != nil else { return }
            // Local entry mirrors localName; re-announce ourselves.
            updateLocalParticipantField { $0.name = localName }
            sendHello()
            if role == .host { broadcastRoster() }
        }
    }
    var localColor: UInt32

    private var handle: OpaquePointer?
    private var boreHandle: OpaquePointer?
    private var pollTimer: DispatchSourceTimer?
    /// Last interval picked by `schedulePump`. Persists across ticks so the
    /// adaptive backoff can step up/down rather than snapping each cycle.
    private var pollIntervalMs: Int = 16
    private var borePumpTimer: Timer?
    private var keepAliveTimer: Timer?

    /// Host-only: transport peer id → user identity (filled on Hello).
    private var transportToIdentity: [UInt32: UserIdentity] = [:]

    private static let keepAliveInterval: TimeInterval = 15

    /// Peer-only auto-reconnect (#61): the host:port of the last successful
    /// join, kept so a dropped connection can be retried without the user
    /// re-entering the share URL. Cleared by `stop()`.
    private var lastJoinHost: String?
    private var lastJoinPort: UInt16 = 0
    private var reconnectTimer: Timer?
    private var reconnectAttempt = 0
    /// Bumped by `stop()` so an in-flight background connect from a
    /// cancelled reconnect can't resurrect a session the user left.
    private var reconnectGeneration = 0
    static let maxReconnectAttempts = 8

    /// Decoded inbound frame + the transport peer id that sent it.
    var onFrame: ((Frame, UInt32) -> Void)?

    /// Peer-only: fired when the host connection drops and auto-reconnect
    /// starts. UI shows a "reconnecting" notice.
    var onReconnectBegan: (() -> Void)?

    /// Peer-only: fired after the transport is re-established, before Hello
    /// is re-sent. The UI layer must reset join-time state here so the
    /// host's re-join snapshot lands in fresh grids instead of appending to
    /// stale ones.
    var onReconnected: (() -> Void)?

    init(identity: UserIdentity = .random(),
         name: String? = nil,
         color: UInt32? = nil)
    {
        self.localIdentity = identity
        self.localName = name ?? SessionManager.savedOrDefaultName()
        self.localColor = color ?? Self.defaultColor(for: identity)
    }

    deinit {
        pollTimer?.cancel()
        borePumpTimer?.invalidate()
        keepAliveTimer?.invalidate()
        reconnectTimer?.invalidate()
        if let h = handle { ct_session_free(h) }
        if let b = boreHandle { ct_bore_free(b) }
    }

    // MARK: lifecycle

    func startHost(port: UInt16 = 0) {
        guard handle == nil else { return }
        role = .host
        accessMode = Self.savedAccessMode()
        sessionKey = SessionKey()
        state = .starting
        guard let h = ct_session_new_host(port) else {
            state = .failed(Self.readLastError()
                ?? "ct_session_new_host failed")
            return
        }
        handle = h
        localPort = ct_session_port(h)
        participants = [Participant(
            identity: localIdentity, role: .host,
            name: localName, color: localColor)]
        state = .running
        startPolling()
        startKeepAlive()
    }

    /// Connect to `host:port`. `host` can be an IP literal or DNS name
    /// (e.g. "bore.pub"). Blocking; returns once the initial TCP handshake
    /// completes or fails.
    func joinPeer(host: String, port: UInt16) {
        guard handle == nil else { return }
        role = .peer
        accessMode = .full
        state = .starting
        let h = host.withCString { cstr in
            ct_session_new_peer(cstr, port)
        }
        guard let h = h else {
            let detail = Self.readLastError() ?? "unknown error"
            state = .failed("\(detail) — host=\(host) port=\(port)")
            return
        }
        handle = h
        lastJoinHost = host
        lastJoinPort = port
        participants = [Participant(
            identity: localIdentity, role: .peer,
            name: localName, color: localColor)]
        state = .running
        startPolling()
        startKeepAlive()
        sendHello()  // tell the host who we are; host broadcasts Roster back
    }

    func stop() {
        pollTimer?.cancel(); pollTimer = nil
        borePumpTimer?.invalidate(); borePumpTimer = nil
        keepAliveTimer?.invalidate(); keepAliveTimer = nil
        reconnectTimer?.invalidate(); reconnectTimer = nil
        reconnectAttempt = 0
        reconnectGeneration += 1
        lastJoinHost = nil
        lastJoinPort = 0
        if let h = handle {
            ct_session_free(h)
            handle = nil
        }
        if let b = boreHandle {
            ct_bore_free(b)
            boreHandle = nil
        }
        participants.removeAll()
        transportToIdentity.removeAll()
        localPort = 0
        publicURL = nil
        lastError = nil
        sessionKey = nil
        state = .idle
        // Always return to host role so the user can start a new session after
        // leaving a peer session. The role is re-assigned correctly by
        // startHost() / joinPeer() whenever a new session begins.
        role = .host
    }

    // MARK: bore tunnel (host only)

    /// `server`: bore relay hostname (empty = ngrok mode). `secret`: bore --secret value (empty = no auth).
    func startBoreTunnel(borePath: String, server: String = "", secret: String = "") {
        NSLog("[ct] startBoreTunnel role=%@ handle=%@ port=%d path=%@ server=%@",
              role == .host ? "host" : "peer",
              boreHandle == nil ? "nil" : "set",
              Int32(localPort),
              borePath,
              server.isEmpty ? "(ngrok)" : server)
        guard role == .host, boreHandle == nil, localPort != 0 else {
            NSLog("[ct] startBoreTunnel early return")
            return
        }
        publicURL = nil
        lastError = nil
        guard let b = ct_bore_new() else {
            lastError = "ct_bore_new failed"
            NSLog("[ct] ct_bore_new returned nil")
            return
        }
        boreHandle = b
        let rc = borePath.withCString { boreCStr in
            server.withCString { serverCStr in
                secret.withCString { secretCStr in
                    ct_bore_start(b, boreCStr, localPort, serverCStr, secretCStr)
                }
            }
        }
        NSLog("[ct] ct_bore_start rc=%d", rc)
        if rc != 0 {
            lastError = "ct_bore_start failed"
            ct_bore_free(b)
            boreHandle = nil
            return
        }
        startBorePumping()
    }

    // MARK: send helpers

    /// Broadcast to every transport peer (no filtering).
    func broadcast(_ frame: Frame) {
        guard let h = handle else { return }
        guard let data = encryptedWireBytes(FrameCodec.encode(frame)) else { return }
        let rc = data.withUnsafeBytes { raw -> Int32 in
            guard let base = raw.baseAddress else { return -1 }
            return ct_session_broadcast(
                h,
                base.assumingMemoryBound(to: UInt8.self),
                data.count)
        }
        if rc != 0 {
            NSLog("[ct] broadcast failed rc=%d bytes=%d", rc, data.count)
        }
    }

    func send(_ frame: Frame, toTransportPeerID peerID: UInt32) {
        guard let h = handle else { return }
        guard let data = encryptedWireBytes(FrameCodec.encode(frame)) else { return }
        let rc = data.withUnsafeBytes { raw -> Int32 in
            guard let base = raw.baseAddress else { return -1 }
            return ct_session_send_to(
                h,
                peerID,
                base.assumingMemoryBound(to: UInt8.self),
                data.count)
        }
        if rc != 0 {
            NSLog("[ct] send_to failed peer=%u bytes=%d err=%@",
                  peerID, data.count, Self.readLastError() ?? "<unknown>")
        }
    }

    /// Returns nil when encryption fails — the frame must be DROPPED, never
    /// silently downgraded to plaintext on an encrypted session.
    private func encryptedWireBytes(_ plain: Data) -> Data? {
        guard let key = sessionKey else { return plain }
        do {
            return try key.encrypt(plain)
        } catch {
            NSLog("[ct] encrypt failed, frame dropped: %@", "\(error)")
            return nil
        }
    }

    func sendHello() {
        broadcast(.hello(
            localIdentity,
            role: role == .host ? .host : .peer,
            color: localColor,
            name: localName))
    }

    func sendCursor(col: UInt16, row: UInt16) {
        broadcast(.cursorPos(localIdentity, col: col, row: row))
    }

    /// Host only: fan PTY output out to every peer.
    func sendPtyOutput(_ bytes: Data) {
        guard role == .host, state == .running, !bytes.isEmpty else { return }
        broadcast(.ptyOutput(bytes))
    }

    /// Host only: broadcast a mode transition. Idempotent — callers should
    /// gate with their own edge detector.
    func sendMode(_ mode: TermMode) {
        guard role == .host, state == .running else { return }
        remoteMode = mode
        broadcast(.modeChange(mode))
    }

    // MARK: tab send helpers (host only)

    /// Host only: announce a new tab (broadcast or directed).
    func sendTabOpen(tabId: UInt32, title: String,
                     toTransportPeerID peerID: UInt32? = nil)
    {
        guard role == .host, state == .running else { return }
        let frame = Frame.tabOpen(tabId: tabId, title: title)
        if let peerID {
            send(frame, toTransportPeerID: peerID)
        } else {
            broadcast(frame)
        }
    }

    /// Host only: announce a tab teardown.
    func sendTabClose(tabId: UInt32) {
        guard role == .host, state == .running else { return }
        broadcast(.tabClose(tabId: tabId))
    }

    /// Announce which tab the local user is currently focused on. Hosts use
    /// this for initial focus hints; peers use it so the host can keep
    /// per-user tab cursor state separate.
    func sendTabFocus(tabId: UInt32,
                      toTransportPeerID peerID: UInt32? = nil)
    {
        guard state == .running else { return }
        let frame = Frame.tabFocus(tabId: tabId)
        if let peerID {
            send(frame, toTransportPeerID: peerID)
        } else {
            broadcast(frame)
        }
    }

    /// Host only: fan a chunk of PTY output for a specific tab to peers.
    func sendTabPtyOutput(tabId: UInt32, data: Data,
                          toTransportPeerID peerID: UInt32? = nil)
    {
        guard role == .host, state == .running, !data.isEmpty else { return }
        let frame = Frame.tabPtyOutput(tabId: tabId, data: data)
        if let peerID {
            send(frame, toTransportPeerID: peerID)
        } else {
            broadcast(frame)
        }
    }

    /// Peer only: ship keystrokes for one tab to the host. The host writes
    /// them only into the matching PTY, so tabs do not share input state.
    func sendTabInput(tabId: UInt32, data: Data) {
        guard role == .peer, state == .running, !data.isEmpty else { return }
        guard accessMode == .full else { return }
        broadcast(.tabInput(tabId: tabId, data: data))
    }

    // MARK: split-pane send helpers

    /// Host only: announce a new split pane inside a tab.
    func sendPaneOpen(tabId: UInt32, paneId: UInt32, axis: SplitAxis,
                      toTransportPeerID peerID: UInt32? = nil)
    {
        guard role == .host, state == .running else { return }
        let frame = Frame.paneOpen(tabId: tabId, paneId: paneId, axis: axis)
        if let peerID { send(frame, toTransportPeerID: peerID) }
        else { broadcast(frame) }
    }

    /// Host only: announce that a split pane was closed.
    func sendPaneClose(tabId: UInt32, paneId: UInt32) {
        guard role == .host, state == .running else { return }
        broadcast(.paneClose(tabId: tabId, paneId: paneId))
    }

    /// Host only: fan PTY output for a specific split pane to peers.
    func sendPanePtyOutput(paneId: UInt32, data: Data,
                           toTransportPeerID peerID: UInt32? = nil)
    {
        guard role == .host, state == .running, !data.isEmpty else { return }
        let frame = Frame.panePtyOutput(paneId: paneId, data: data)
        if let peerID { send(frame, toTransportPeerID: peerID) }
        else { broadcast(frame) }
    }

    /// Peer only: send keystrokes for a specific split pane to the host.
    func sendPaneInput(paneId: UInt32, data: Data) {
        guard role == .peer, state == .running, !data.isEmpty else { return }
        guard accessMode == .full else { return }
        broadcast(.paneInput(paneId: paneId, data: data))
    }

    /// Broadcast the local user's cursor position within a pane.
    func sendPaneCursor(paneId: UInt32, col: UInt16, row: UInt16) {
        guard state == .running else { return }
        broadcast(.paneCursorPos(localIdentity, paneId: paneId, col: col, row: row))
    }

    /// Host only: relay a peer's pane cursor update to all peers (including
    /// the originator, which will filter its own identity on receipt).
    func relayPaneCursor(from identity: UserIdentity, paneId: UInt32,
                         col: UInt16, row: UInt16)
    {
        guard role == .host, state == .running else { return }
        broadcast(.paneCursorPos(identity, paneId: paneId, col: col, row: row))
    }

    /// Host only: change the access policy and announce it to all peers.
    /// Persisted via `UserDefaults` so subsequent sessions remember the
    /// last preference. Safe to call before any peer has connected — the
    /// stored value is sent automatically when peers say Hello.
    func setAccessMode(_ mode: AccessMode) {
        guard role == .host else { return }
        accessMode = mode
        Self.persistAccessMode(mode)
        if state == .running {
            broadcast(.accessMode(mode))
        }
    }

    /// Host only: announce the current access mode unconditionally. Used
    /// after a peer Hello so a fresh joiner learns the policy without
    /// waiting for the next toggle.
    func broadcastAccessMode() {
        guard role == .host, state == .running else { return }
        broadcast(.accessMode(accessMode))
    }

    /// Peer only: ask the host for full access. Harmless if already full —
    /// the host simply ignores a request when the session isn't view-only.
    func sendControlRequest() {
        guard role == .peer, state == .running else { return }
        broadcast(.requestControl(localIdentity))
    }

    /// Host only: decline a peer's control request so they get explicit
    /// feedback rather than silence. Granting is handled by the existing
    /// `setAccessMode(.full)` path — no separate "granted" frame is needed
    /// because the access-mode broadcast already tells the peer.
    func denyControlRequest(_ identity: UserIdentity) {
        guard role == .host, state == .running else { return }
        guard let peerID = transportToIdentity.first(where: { $0.value == identity })?.key
        else { return }
        send(.controlDenied(identity), toTransportPeerID: peerID)
    }

    /// Host only: remove a participant by identity. Sends a kick frame so the
    /// peer can display a "you were removed" message, then closes their socket.
    func kickPeer(_ identity: UserIdentity) {
        guard role == .host,
              state == .running,
              identity != localIdentity else { return }
        guard let peerID = transportToIdentity.first(where: { $0.value == identity })?.key,
              let h = handle else { return }

        // Notify the peer before the socket drops (TCP ordering guarantees delivery).
        send(.kick(identity), toTransportPeerID: peerID)

        // Close the TCP connection; reader thread fires peer_disconnected async.
        ct_session_drop_peer(h, peerID)

        // Eagerly update local state so the UI is immediately responsive.
        // The async peer_disconnected event will be a no-op (identity already removed).
        transportToIdentity.removeValue(forKey: peerID)
        participants.removeAll { $0.identity == identity }
        broadcastRoster()
    }

    /// Peer only: ship keystroke bytes to the host as an opaque `inputOp`
    /// payload. (Full CRDT merge is a future step; Phase 3 uses this as a
    /// "raw-bytes passthrough" so end-to-end shared typing works.) In
    /// view-only mode this is a no-op so a misbehaving caller can't bypass
    /// the UI gate.
    func sendInputBytes(_ bytes: Data) {
        guard role == .peer, state == .running, !bytes.isEmpty else { return }
        guard accessMode == .full else { return }
        broadcast(.inputOp(bytes))
    }

    func sendEditorOpen(docId: UInt64, path: String, snapshot: Data) {
        guard role == .host, state == .running else { return }
        broadcast(.editorOpen(docId: docId, path: path, snapshot: snapshot))
    }

    func sendEditorOp(docId: UInt64, opBytes: Data) {
        guard state == .running, !opBytes.isEmpty else { return }
        broadcast(.editorOp(docId: docId, opBytes: opBytes))
    }

    func sendEditorPresence(docId: UInt64,
                            userId: UInt32,
                            anchor: CrdtId?,
                            selectionAnchor: CrdtId?)
    {
        guard state == .running else { return }
        broadcast(.editorPresence(
            docId: docId,
            userId: userId,
            anchor: anchor,
            selectionAnchor: selectionAnchor))
    }

    func sendEditorSave(docId: UInt64) {
        guard state == .running else { return }
        broadcast(.editorSave(docId: docId))
    }

    func sendEditorSaved(docId: UInt64, rev: UInt32) {
        guard role == .host, state == .running else { return }
        broadcast(.editorSaved(docId: docId, rev: rev))
    }

    func sendEditorClose(docId: UInt64) {
        guard state == .running else { return }
        broadcast(.editorClose(docId: docId))
    }

    func sendFileSyncDelta(_ delta: FSSyncDelta, toTransportPeerID peerID: UInt32? = nil) {
        guard role == .host, state == .running else { return }
        let frame = Frame.fsDelta(delta)
        if let peerID {
            send(frame, toTransportPeerID: peerID)
        } else {
            broadcast(frame)
        }
    }

    func sendFileSyncSnapshot(_ entries: [FSSnapshotEntry],
                              toTransportPeerID peerID: UInt32? = nil)
    {
        guard role == .host, state == .running else { return }
        let frame = Frame.fsSnapshot(entries)
        if let peerID {
            send(frame, toTransportPeerID: peerID)
        } else {
            broadcast(frame)
        }
    }

    func sendHeartbeat() {
        guard state == .running else { return }
        broadcast(.heartbeat)
    }

    // MARK: polling

    private func startPolling() {
        pollTimer?.cancel()
        let t = DispatchSource.makeTimerSource(queue: .main)
        pollTimer = t
        pollIntervalMs = 16
        t.setEventHandler { [weak self] in
            MainActor.assumeIsolated {
                guard let self = self else { return }
                let drained = self.pump()
                self.schedulePump(drained: drained)
            }
        }
        t.schedule(deadline: .now() + .milliseconds(pollIntervalMs))
        t.resume()
    }

    /// Pick the next pump interval based on activity. Backoff schedule:
    /// 16 ms (active) → 33 ms → 66 ms (steady idle, peer connected),
    /// or 200 ms when no remote peer is connected. Any drain > 0 snaps
    /// back to 16 ms so interactive latency stays unaffected. Cheap: just
    /// re-arms the existing DispatchSourceTimer.
    private func schedulePump(drained: Int) {
        guard let t = pollTimer else { return }
        let next: Int
        if drained > 0 {
            next = 16
        } else if participants.count <= 1 {
            // No remote peers — `ct_session_poll` can't produce frames.
            next = 200
        } else {
            switch pollIntervalMs {
            case ..<33: next = 33
            case 33..<66: next = 66
            default: next = 66
            }
        }
        pollIntervalMs = next
        t.schedule(deadline: .now() + .milliseconds(next))
    }

    private func startKeepAlive() {
        keepAliveTimer?.invalidate()
        keepAliveTimer = Timer.scheduledTimer(
            withTimeInterval: Self.keepAliveInterval,
            repeats: true
        ) { [weak self] _ in
            MainActor.assumeIsolated { self?.sendHeartbeat() }
        }
    }

    private var borePumpTickCount: Int = 0
    private func startBorePumping() {
        NSLog("[ct] startBorePumping scheduling timer")
        borePumpTickCount = 0
        borePumpTimer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] t in
            MainActor.assumeIsolated {
                guard let self = self, let b = self.boreHandle else {
                    NSLog("[ct] bore pump timer: no handle, invalidating")
                    t.invalidate()
                    return
                }
                self.borePumpTickCount += 1
                var buf = [UInt8](repeating: 0, count: 256)
                let n = buf.withUnsafeMutableBufferPointer { p -> Int in
                    Int(ct_bore_pump(b, p.baseAddress, p.count))
                }
                if self.borePumpTickCount <= 5 || self.borePumpTickCount % 5 == 0 {
                    NSLog("[ct] bore pump tick=%d rc=%d", self.borePumpTickCount, n)
                }
                if n > 0 {
                    var url = String(bytes: buf.prefix(min(n, buf.count)), encoding: .utf8)
                    if let keyFrag = self.sessionKey?.base64url {
                        url = url.map { "cotty://join?addr=\($0)&k=\(keyFrag)" }
                    } else {
                        url = url.map { "cotty://join?addr=\($0)" }
                    }
                    self.publicURL = url
                    NSLog("[ct] bore url ready: %@", url ?? "<nil>")
                    t.invalidate()
                } else if n < 0 {
                    // Snapshot whatever bore has printed so we can diagnose.
                    var dbuf = [UInt8](repeating: 0, count: 4096)
                    let dlen = dbuf.withUnsafeMutableBufferPointer { p -> Int in
                        Int(ct_bore_debug(b, p.baseAddress, p.count))
                    }
                    let preview = String(bytes: dbuf.prefix(min(dlen, dbuf.count)),
                                         encoding: .utf8) ?? "<binary>"
                    let trimmed = preview.trimmingCharacters(in: .whitespacesAndNewlines)
                    self.lastError = trimmed.isEmpty
                        ? "bore exited before reporting a public URL"
                        : trimmed
                    NSLog("[ct] bore pump rc=-1 bufferedLen=%d preview=%@",
                          dlen, preview)
                    t.invalidate()
                    // Free the handle so startBoreTunnel can be called again (retry).
                    ct_bore_free(b)
                    self.boreHandle = nil
                }
            }
        }
    }

    @discardableResult
    private func pump() -> Int {
        return drainFrames() + drainEvents()
    }

    @discardableResult
    private func drainEvents() -> Int {
        var count = 0
        for _ in 0..<32 {
            // Re-check every iteration: an event handler may have called
            // stop() (e.g. peer-side on host disconnect), freeing the handle.
            guard let h = handle else { return count }
            var kind: UInt8 = 0
            var peerID: UInt32 = 0
            let r = ct_session_poll_event(h, &kind, &peerID)
            if r == 0 { return count }
            count += 1
            switch kind {
            case 0: handleConnected(peerID)
            case 1: handleDisconnected(peerID)
            default: break
            }
        }
        return count
    }

    @discardableResult
    private func drainFrames() -> Int {
        var buf = [UInt8](repeating: 0, count: 64 * 1024)
        var count = 0
        for _ in 0..<64 {
            guard let h = handle else { return count }
            var peerID: UInt32 = 0
            let n = buf.withUnsafeMutableBufferPointer { p -> Int in
                Int(ct_session_poll(h, p.baseAddress, p.count, &peerID))
            }
            if n == 0 { return count }
            if n > buf.count {
                buf = [UInt8](repeating: 0, count: n)
                continue
            }
            count += 1
            let wire = Data(buf.prefix(n))
            do {
                let plain: Data
                if let key = sessionKey {
                    plain = try key.decrypt(wire)
                } else {
                    plain = wire
                }
                let frame = try FrameCodec.decode(plain)
                handleFrame(frame, from: peerID)
            } catch {
                lastError = "decode: \(error)"
            }
        }
        return count
    }

    // MARK: event / frame handlers

    private func handleConnected(_ peerID: UInt32) {
        // Host: a peer's TCP just landed; roster updates on their Hello.
        // On the peer side the one "connected" event is the host socket —
        // no state change needed until the host's Roster arrives.
        _ = peerID
    }

    private func handleDisconnected(_ peerID: UInt32) {
        if role == .host {
            if let gone = transportToIdentity.removeValue(forKey: peerID) {
                // A reconnecting peer may already be back on a new transport
                // connection before the old socket's death is noticed — only
                // drop them from the roster when this was their last one.
                if !transportToIdentity.values.contains(gone) {
                    participants.removeAll { $0.identity == gone }
                }
                broadcastRoster()
            }
        } else {
            // Peer-side: the host connection dropped. Auto-retry the join
            // with backoff (#61); tear down only if we never had a target.
            if lastJoinHost != nil {
                beginReconnect()
            } else {
                stop()
                state = .disconnected
            }
        }
    }

    // MARK: reconnect (peer only)

    /// Backoff before reconnect `attempt` (1-based): 1s, 2s, 4s, …, 30s cap.
    private static func reconnectDelay(attempt: Int) -> TimeInterval {
        min(30, pow(2, Double(attempt - 1)))
    }

    /// Tear down the dead transport but keep identity, session key, role,
    /// and roster so the session can resume in place.
    private func beginReconnect() {
        pollTimer?.cancel(); pollTimer = nil
        keepAliveTimer?.invalidate(); keepAliveTimer = nil
        if let h = handle {
            ct_session_free(h)
            handle = nil
        }
        reconnectAttempt = 0
        onReconnectBegan?()
        scheduleReconnect()
    }

    private func scheduleReconnect() {
        reconnectAttempt += 1
        guard reconnectAttempt <= Self.maxReconnectAttempts else {
            NSLog("[ct] reconnect gave up after %d attempts", Self.maxReconnectAttempts)
            stop()
            state = .disconnected
            return
        }
        state = .reconnecting(attempt: reconnectAttempt)
        let delay = Self.reconnectDelay(attempt: reconnectAttempt)
        NSLog("[ct] reconnect attempt %d/%d in %.0fs",
              reconnectAttempt, Self.maxReconnectAttempts, delay)
        reconnectTimer?.invalidate()
        reconnectTimer = Timer.scheduledTimer(
            withTimeInterval: delay,
            repeats: false
        ) { [weak self] _ in
            MainActor.assumeIsolated { self?.attemptReconnect() }
        }
    }

    private func attemptReconnect() {
        guard case .reconnecting = state, let host = lastJoinHost else { return }
        let port = lastJoinPort
        let generation = reconnectGeneration
        // Connect off the main actor — a vanished host can leave the TCP
        // handshake hanging far longer than any acceptable UI stall. The
        // handle crosses back as a bit pattern because OpaquePointer is
        // not Sendable.
        Task.detached(priority: .userInitiated) { [weak self] in
            let bits = host.withCString { cstr in
                Int(bitPattern: ct_session_new_peer(cstr, port))
            }
            guard let self else {
                // Manager died while connecting; don't leak the socket.
                if let h = OpaquePointer(bitPattern: bits) { ct_session_free(h) }
                return
            }
            await self.finishReconnectAttempt(handleBits: bits, generation: generation)
        }
    }

    private func finishReconnectAttempt(handleBits: Int, generation: Int) {
        let newHandle = OpaquePointer(bitPattern: handleBits)
        // The user stopped or left the session while the connect was in
        // flight — discard the orphaned connection.
        guard generation == reconnectGeneration, case .reconnecting = state else {
            if let h = newHandle { ct_session_free(h) }
            return
        }
        guard let h = newHandle else {
            NSLog("[ct] reconnect attempt %d failed: %@",
                  reconnectAttempt, Self.readLastError() ?? "unknown error")
            scheduleReconnect()
            return
        }
        NSLog("[ct] reconnected after %d attempt(s)", reconnectAttempt)
        handle = h
        reconnectAttempt = 0
        state = .running
        startPolling()
        startKeepAlive()
        // Let the UI reset join-time state before Hello triggers the host's
        // re-join snapshot.
        onReconnected?()
        sendHello()
    }

    private func handleFrame(_ frame: Frame, from peerID: UInt32) {
        switch frame {
        case .hello(let id, let helloRole, let color, let name):
            if role == .host {
                transportToIdentity[peerID] = id
                upsertParticipant(identity: id, role: helloRole,
                                  name: name, color: color)
                broadcastRoster()
            }
        case .roster(let entries):
            if role == .peer {
                // Peer: replace participants with authoritative list.
                var next: [Participant] = entries.map {
                    Participant(identity: $0.identity,
                                role: $0.role,
                                name: $0.name,
                                color: $0.color)
                }
                // Make sure our own entry is present with our current name.
                if !next.contains(where: { $0.identity == localIdentity }) {
                    next.append(Participant(
                        identity: localIdentity, role: .peer,
                        name: localName, color: localColor))
                }
                if let localEntry = next.first(where: { $0.identity == localIdentity }) {
                    localColor = localEntry.color
                }
                participants = next
            }
        case .modeChange(let m):
            if role == .peer { remoteMode = m }
        case .accessMode(let m):
            if role == .peer { accessMode = m }
        case .heartbeat:
            break
        case .kick(let id):
            _ = id  // ContentView.handleInbound handles teardown and notification
        default:
            break
        }
        onFrame?(frame, peerID)
    }

    // MARK: participants / roster

    private func upsertParticipant(identity: UserIdentity,
                                   role helloRole: SessionRole,
                                   name: String,
                                   color: UInt32)
    {
        let resolvedColor = resolvedParticipantColor(
            for: identity,
            preferredColor: color)
        if let i = participants.firstIndex(where: { $0.identity == identity }) {
            participants[i].role = helloRole
            participants[i].name = name
            participants[i].color = resolvedColor
        } else {
            participants.append(Participant(
                identity: identity, role: helloRole,
                name: name, color: resolvedColor))
        }
    }

    /// Override a participant's rendered cursor color. Used by the UI layer to
    /// apply theme-derived (per-viewer) colors; no-op if unchanged.
    func setParticipantColor(_ identity: UserIdentity, to color: UInt32) {
        if let i = participants.firstIndex(where: { $0.identity == identity }),
           participants[i].color != color {
            participants[i].color = color
        }
    }

    private func resolvedParticipantColor(for identity: UserIdentity,
                                          preferredColor: UInt32) -> UInt32
    {
        let usedColors = Set(
            participants
                .filter { $0.identity != identity }
                .map(\.color))
        if !usedColors.contains(preferredColor) {
            return preferredColor
        }

        let palette = Self.participantPalette
        guard !palette.isEmpty else { return preferredColor }

        let start = Int(Self.colorHash(for: identity) % UInt32(palette.count))
        for offset in 0..<palette.count {
            let candidate = palette[(start + offset) % palette.count]
            if !usedColors.contains(candidate) {
                return candidate
            }
        }
        return preferredColor
    }

    private func updateLocalParticipantField(_ mutate: (inout Participant) -> Void) {
        if let i = participants.firstIndex(where: { $0.identity == localIdentity }) {
            mutate(&participants[i])
        }
    }

    /// Host only: broadcast the current full roster to all peers.
    private func broadcastRoster() {
        guard role == .host else { return }
        let entries = participants.map {
            RosterEntry(identity: $0.identity, role: $0.role,
                        color: $0.color, name: $0.name)
        }
        broadcast(.roster(entries))
    }

    // MARK: persisted name

    static let nameDefaultsKey = "CoTTY.displayName"

    /// UserDefaults key for the host-side access policy. Mirrors the
    /// shape used for `nameDefaultsKey`; the sidebar Picker writes this.
    static let accessModeDefaultsKey = "CoTTY.accessMode"

    nonisolated static func savedAccessMode() -> AccessMode {
        let raw = UserDefaults.standard.integer(forKey: accessModeDefaultsKey)
        guard let mode = AccessMode(rawValue: UInt8(clamping: raw)) else {
            return .full
        }
        return mode
    }

    nonisolated static func persistAccessMode(_ mode: AccessMode) {
        UserDefaults.standard.set(Int(mode.rawValue), forKey: accessModeDefaultsKey)
    }

    /// Read the last-error slot populated by the Zig C ABI. Returns nil
    /// if empty.
    nonisolated static func readLastError() -> String? {
        var buf = [UInt8](repeating: 0, count: 512)
        let n = buf.withUnsafeMutableBufferPointer { p -> Int in
            Int(ct_last_error(p.baseAddress, p.count))
        }
        if n == 0 { return nil }
        let len = min(n, buf.count)
        return String(bytes: buf.prefix(len), encoding: .utf8)
    }

    nonisolated static func savedOrDefaultName() -> String {
        if let s = UserDefaults.standard.string(forKey: nameDefaultsKey),
           !s.isEmpty
        {
            return s
        }
        return NSUserName()
    }

    func persistName() {
        UserDefaults.standard.set(localName, forKey: Self.nameDefaultsKey)
    }

    nonisolated static var participantPalette: [UInt32] {
        [
            0xFF3B30, // red
            0xFFD60A, // yellow
            0x32D74B, // green
            0x00C7BE, // teal
            0x64D2FF, // cyan
            0x0A84FF, // blue
            0x5E5CE6, // indigo
            0xBF5AF2, // purple
            0xFF375F, // pink
            0xFF9F0A, // orange
        ]
    }

    nonisolated static func defaultColor(for identity: UserIdentity) -> UInt32 {
        let palette = participantPalette
        return palette[Int(colorHash(for: identity) % UInt32(palette.count))]
    }

    nonisolated static func editorUserID(for identity: UserIdentity) -> UInt32 {
        let hash = colorHash(for: identity)
        // Reserve 0 for deterministic snapshot-loaded CRDT items so anchor
        // ids from initial file contents are replica-stable across peers.
        return hash == 0 ? 1 : hash
    }

    func participant(forEditorUserID editorUserID: UInt32) -> Participant? {
        participants.first { Self.editorUserID(for: $0.identity) == editorUserID }
    }

    func identity(forTransportPeerID peerID: UInt32) -> UserIdentity? {
        if role == .host {
            return transportToIdentity[peerID]
        }
        return nil
    }

    nonisolated static func colorHash(for identity: UserIdentity) -> UInt32 {
        var hash: UInt32 = 2166136261
        for byte in identity.bytes {
            hash ^= UInt32(byte)
            hash &*= 16777619
        }
        return hash
    }
}
