import CryptoKit
import Foundation

/// A 256-bit ChaCha20-Poly1305 session key. Generated by the host, embedded
/// in the share URL as a base64url fragment (#k=...) so the relay never sees
/// it. Peers extract it from the URL before joining.
struct SessionKey {
    private let key: SymmetricKey

    init() {
        key = SymmetricKey(size: .bits256)
    }

    init?(base64url: String) {
        var b64 = base64url
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        while b64.count % 4 != 0 { b64 += "=" }
        guard let data = Data(base64Encoded: b64), data.count == 32 else { return nil }
        key = SymmetricKey(data: data)
    }

    var base64url: String {
        key.withUnsafeBytes { Data($0) }
            .base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    /// Encrypts plaintext. Returns nonce (12 B) + ciphertext + tag (16 B).
    func encrypt(_ data: Data) throws -> Data {
        try ChaChaPoly.seal(data, using: key).combined
    }

    /// Decrypts a blob produced by `encrypt`.
    func decrypt(_ data: Data) throws -> Data {
        try ChaChaPoly.open(ChaChaPoly.SealedBox(combined: data), using: key)
    }
}
